Repository honeycombio/honeycomb-opentelemetry-web, pull requests merged in 2024-04, with the labels that each got.

#118 docs: README.md update
  README.md
Labels: type: documentation, merge at will

#124 rel: Release v0.1.1
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/version.ts
Labels: no-changelog, version: no bump

#129 feat: Add s/m/l screen size resource attribute
  README.md
  src/browser-attributes-resource.ts
  test/browser-attributes-resource.test.ts
Labels: type: enhancement, version: bump minor
