Repository honeycombio/honeycomb-opentelemetry-web, pull requests merged in 2024-07, with the labels that each got.

#189 feat: Update example to nest spans.
  examples/hello-world-web/index.js
  examples/hello-world-web/package-lock.json
  examples/hello-world-web/package.json
Labels: type: maintenance

#186 feat: Add Global Error Instrumentation
  src/global-errors-autoinstrumentation.ts
  src/honeycomb-otel-sdk.ts
  src/types.ts
  test/global-errors-instrumentation.test.ts
  test/honeycomb-debug.test.ts
Labels: type: enhancement

#193 docs: update vulnerability reporting process
  SECURITY.md
Labels: type: documentation, version: no bump

#197 rel: Version 0.5.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/version.ts
Labels: type: maintenance, no-changelog, version: no bump

#209 fix: npm audit vulnerability
  package-lock.json
Labels: type: maintenance, version: bump patch

#210 chore: dependabot should ignore major version upgrades
  .github/dependabot.yml
Labels: type: maintenance, no-changelog, version: no bump

#212 feat: Support multiple span processors
  README.md
  src/span-processor-builder.ts
  src/types.ts
  test/span-processor-builder.test.ts
Labels: type: enhancement, version: bump minor
