Repository honeycombio/honeycomb-opentelemetry-web, pull requests merged in 2024-03, with the labels that each got.

#107 maint: Update ubuntu image in workflows to latest
  .circleci/config.yml
Labels: type: maintenance, version: no bump

#106 feat: Auto-enable web vitals instrumentation
  examples/custom-with-collector-ts/src/index.ts
  examples/hello-world-web/index.js
  smoke-tests/smoke-e2e.bats
  src/honeycomb-otel-sdk.ts
  src/types.ts
  src/util.ts
  src/web-vitals-autoinstrumentation.ts
  test/honeycomb-debug.test.ts
Labels: type: enhancement, version: bump minor

#109 docs: README updates before releasing beta
  README.md
  docs/web-vitals.md
Labels: type: documentation, no-changelog, version: no bump

#117 docs: Update README.md to include link to docs site page
  README.md
Labels: type: documentation, merge at will
