Repository honeycombio/honeycomb-opentelemetry-web, pull requests merged in 2024-02, with the labels that each got.

#60 fix(ci): update publish steps to depend on smoke tests
  .circleci/config.yml
Labels: type: bug, type: maintenance, no-changelog

#62 feat: allow custom override of entry page attributes
  src/entry-page-resource.ts
  src/honeycomb-otel-sdk.ts
  src/types.ts
  test/entry-page-resource.test.ts
  test/honeycomb-otel-sdk.test.ts
Labels: type: enhancement, version: bump minor

#70 feat: Add DeterministicSampler for easier sampling
  smoke-tests/smoke-e2e.bats
  src/deterministic-sampler.ts
  src/honeycomb-debug.ts
  src/honeycomb-otel-sdk.ts
  src/types.ts
  src/util.ts
  test/deterministic-sampler.test.ts
  test/honeycomb-debug.test.ts
  test/util.test.ts
Labels: type: enhancement, version: bump minor

#72 feat: add AlwaysOffSampler
  src/deterministic-sampler.ts
  src/types.ts
  src/util.ts
  test/deterministic-sampler.test.ts
  test/util.test.ts
Labels: type: enhancement, version: bump minor

#34 feat: ✨ add support for plain objects when initializing resource
  src/honeycomb-otel-sdk.ts
  src/merge-resources.ts
  src/types.ts
  test/honeycomb-otel-sdk.test.ts
  test/merge-resources.test.ts
Labels: type: enhancement, version: bump minor

#71 maint: test and local dev notes cleanup
  DEVELOPING.md
  Dockerfile
  smoke-tests/smoke-e2e.bats
Labels: type: maintenance

#77 feat: ✨ Add `skipOptionsValidation` option and validate options
  src/honeycomb-debug.ts
  src/honeycomb-otel-sdk.ts
  src/types.ts
  src/util.ts
  src/validate-options.ts
  test/honeycomb-debug.test.ts
  test/validate-options.test.ts
Labels: type: enhancement, version: bump minor

#81 feat: add localVisualizations for link to Honeycomb trace
  README.md
  package-lock.json
  package.json
  src/composite-exporter.ts
  src/console-trace-link-exporter.ts
  src/span-processor-builder.ts
  src/types.ts
  src/util.ts
  src/validate-options.ts
  test/console-trace-link-exporter.test.ts
Labels: type: enhancement, version: bump minor

#85 maint: build out smoke test with more detailed example app
  Dockerfile.smoke
  Makefile
  cypress.config.ts
  cypress/e2e/spec.cy.ts
  docker-compose.yml
  examples/custom-with-collector-ts/README.md
  examples/custom-with-collector-ts/package-lock.json
  examples/custom-with-collector-ts/package.json
  examples/custom-with-collector-ts/src/index.html
  examples/custom-with-collector-ts/src/index.ts
  examples/custom-with-collector-ts/tsconfig.json
  examples/custom-with-collector-ts/webpack.config.js
  examples/hello-world-web/index.js
  package.json
  smoke-tests/collector/otel-collector-config.yaml
  smoke-tests/smoke-e2e.bats
  tsconfig.eslint.json
Labels: type: maintenance

#87 rel: prep v0.0.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: no-changelog

#88 maint: add releaseyml for generated release notes
  .github/release.yml
Labels: type: maintenance, no-changelog

#84 feat: initial web vitals instrumentation
  examples/hello-world-web/index.js
  package-lock.json
  package.json
  src/index.ts
  src/web-vitals-autoinstrumentation.ts
  test/web-vitals-instrumentation.test.ts
Labels: type: enhancement

#90 fix: update version and add version change to releasing doc
  RELEASING.md
  src/version.ts
  test/version.test.ts
Labels: type: bug

#91 feat: ✨ Config for web vitals
  src/web-vitals-autoinstrumentation.ts
  test/web-vitals-instrumentation.test.ts
Labels: type: enhancement

#92 docs: add JS docs for web vitals instrumentation
  examples/custom-with-collector-ts/package-lock.json
  src/web-vitals-autoinstrumentation.ts
Labels: type: documentation

#93 rel: v0.0.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/version.ts
Labels: no-changelog, version: no bump
