Repository honeycombio/honeycomb-opentelemetry-web, pull requests merged in 2024-08, with the labels that each got.

#191 feat: Add LOAF support for onINP
  packages/honeycomb-opentelemetry-web/examples/hello-world-web/index.js
  packages/honeycomb-opentelemetry-web/package-lock.json
  packages/honeycomb-opentelemetry-web/package.json
  packages/honeycomb-opentelemetry-web/src/web-vitals-autoinstrumentation.ts
  packages/honeycomb-opentelemetry-web/test/web-vitals-instrumentation.test.ts
  packages/honeycomb-react-user-instrumentation/package-lock.json
  packages/honeycomb-react-user-instrumentation/package.json
Labels: type: enhancement, version: bump minor

#234 rel: honeycomb-opentelemetry-web@v0.6.0
  CHANGELOG.md
  packages/honeycomb-opentelemetry-web/package-lock.json
  packages/honeycomb-opentelemetry-web/package.json
  packages/honeycomb-opentelemetry-web/src/version.ts
Labels: no-changelog, version: no bump

#239 chore: update gitignore paths
  .gitignore
Labels: no-changelog, version: no bump

#242 chore: Update readme links to docs
  README.md
Labels: type: documentation, version: bump patch
