Repository honeycombio/honeycomb-opentelemetry-web, pull requests merged in 2025-01, with the labels that each got.

#446 docs: Docs for recordException function
  README.md
  packages/honeycomb-opentelemetry-web/src/global-errors-autoinstrumentation.ts
Labels: type: documentation, version: no bump

#447 feat(error-autoinstrumentation): Add applyCustomAttribitesToSpan config option
  README.md
  packages/honeycomb-opentelemetry-web/src/global-errors-autoinstrumentation.ts
  packages/honeycomb-opentelemetry-web/test/global-errors-instrumentation.test.ts
Labels: type: enhancement, version: bump minor

#448 rel: Releasing v0.12.0
  packages/honeycomb-opentelemetry-web/CHANGELOG.md
  packages/honeycomb-opentelemetry-web/package-lock.json
  packages/honeycomb-opentelemetry-web/package.json
  packages/honeycomb-opentelemetry-web/src/version.ts
Labels: type: maintenance, no-changelog, version: no bump
