Repository honeycombio/honeycomb-opentelemetry-web, pull requests merged in 2025-03, with the labels that each got.

#484 rel: Releasing v0.14.0
  packages/honeycomb-opentelemetry-web/CHANGELOG.md
  packages/honeycomb-opentelemetry-web/package-lock.json
  packages/honeycomb-opentelemetry-web/package.json
  packages/honeycomb-opentelemetry-web/src/version.ts
Labels: type: maintenance, no-changelog, version: no bump

#493 maint: Peer dependencies and testing for v2 network instrumentation
  packages/honeycomb-opentelemetry-web/Makefile
  packages/honeycomb-opentelemetry-web/cypress/e2e/spec.cy.ts
  packages/honeycomb-opentelemetry-web/examples/custom-with-collector-ts/package-lock.json
  packages/honeycomb-opentelemetry-web/examples/custom-with-collector-ts/package.json
  packages/honeycomb-opentelemetry-web/examples/custom-with-collector-ts/src/index.html
  packages/honeycomb-opentelemetry-web/examples/custom-with-collector-ts/src/index.ts
  packages/honeycomb-opentelemetry-web/examples/hello-world-web/package-lock.json
  packages/honeycomb-opentelemetry-web/examples/hello-world-web/package.json
  packages/honeycomb-opentelemetry-web/package-lock.json
  packages/honeycomb-opentelemetry-web/package.json
  packages/honeycomb-opentelemetry-web/smoke-tests/smoke-e2e.bats
Labels: type: maintenance

#502 feat: Export types and BaggageSpanProcessor
  packages/honeycomb-opentelemetry-web/src/index.ts
Labels: type: enhancement
