Repository honeycombio/honeycomb-opentelemetry-web, pull requests merged in 2025-04, with the labels that each got.

#507 maint: Upgrade @opentelemetry/core to v2
  packages/honeycomb-opentelemetry-web/package-lock.json
  packages/honeycomb-opentelemetry-web/package.json
Labels: type: maintenance, version: bump minor

#508 rel: v0.16.0
  packages/honeycomb-opentelemetry-web/CHANGELOG.md
  packages/honeycomb-opentelemetry-web/README.md
  packages/honeycomb-opentelemetry-web/package-lock.json
  packages/honeycomb-opentelemetry-web/package.json
  packages/honeycomb-opentelemetry-web/src/version.ts
Labels: no-changelog, version: no bump

#510 feat: add an option to disable automatic browser attributes
  packages/honeycomb-opentelemetry-web/src/configure-resource-attributes.ts
  packages/honeycomb-opentelemetry-web/src/configure-span-processors.ts
  packages/honeycomb-opentelemetry-web/src/types.ts
  packages/honeycomb-opentelemetry-web/test/honeycomb-otel-sdk.test.ts
Labels: type: enhancement, version: bump minor

#511 rel: v0.17.0
  packages/honeycomb-opentelemetry-web/CHANGELOG.md
  packages/honeycomb-opentelemetry-web/package-lock.json
  packages/honeycomb-opentelemetry-web/package.json
  packages/honeycomb-opentelemetry-web/src/version.ts
Labels: no-changelog, version: no bump

#517 fix: explicitly add default resource attributes
  packages/honeycomb-opentelemetry-web/smoke-tests/smoke-e2e.bats
  packages/honeycomb-opentelemetry-web/src/base-otel-sdk.ts
  packages/honeycomb-opentelemetry-web/test/honeycomb-otel-sdk.test.ts
Labels: type: bug, version: bump patch

#518 fix: Add repository to package.json
  packages/honeycomb-opentelemetry-web/package.json
Labels: version: no bump

#519 rel: v0.17.1
  packages/honeycomb-opentelemetry-web/CHANGELOG.md
  packages/honeycomb-opentelemetry-web/README.md
  packages/honeycomb-opentelemetry-web/package-lock.json
  packages/honeycomb-opentelemetry-web/package.json
  packages/honeycomb-opentelemetry-web/src/version.ts
Labels: no-changelog, version: no bump
